[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
staking_pepe = "9Mq2JHE2c38LTioLQYjqbLDd4jJkgftLj83VYiTYrfnJ"
x3_pepe = "6hFfJP3EgJe8mL9rhBjXWhruJWHBaWnt8gvej14xDUuz"

[programs.devnet]
staking_pepe = "9Mq2JHE2c38LTioLQYjqbLDd4jJkgftLj83VYiTYrfnJ"
x3_pepe = "6hFfJP3EgJe8mL9rhBjXWhruJWHBaWnt8gvej14xDUuz"

[programs.localnet]
staking_pepe = "9Mq2JHE2c38LTioLQYjqbLDd4jJkgftLj83VYiTYrfnJ"
x3_pepe = "6hFfJP3EgJe8mL9rhBjXWhruJWHBaWnt8gvej14xDUuz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
